"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../dashboard.module.css";
type Group={id:string;name:string;is_owner?:boolean};
type Competition={id:string;name:string;sport:string;game_type:string;season:string;players:number};
export default function MyArena(){
 const [user,setUser]=useState<{email:string;nickname?:string}|null>(null); const [groups,setGroups]=useState<Group[]>([]); const [selected,setSelected]=useState(""); const [games,setGames]=useState<Competition[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const a=await fetch("/api/arena/auth",{cache:"no-store"});const ad=await a.json();if(!ad.user){location.replace("/arena/sign-in");return;}setUser(ad.user);const g=await fetch("/api/arena/groups",{cache:"no-store"});const gd=await g.json();setGroups(gd.groups||[]);if(gd.groups?.[0])setSelected(gd.groups[0].id);}finally{setLoading(false);}})();},[]);
 useEffect(()=>{if(!selected)return;fetch(`/api/arena/competitions?groupId=${selected}`,{cache:"no-store"}).then(r=>r.ok?r.json():{competitions:[]}).then(d=>setGames(d.competitions||[]));},[selected]);
 const group=groups.find(g=>g.id===selected);
 return <main className={styles.page}><header className={styles.header}><Link className="brand" href="/" aria-label="Finals Atlas home"><img className="brand-mark" src="/icon.svg" alt="" /><span className="brand-name"><span>FINALS</span><span>ATLAS</span></span></Link><nav className={styles.nav}><Link href="/arena">Arena overview</Link><Link href="/arena/me">My Arena</Link></nav></header><div className={styles.shell}><section className={styles.hero}><div><span className={styles.kicker}>PERSONAL ARENA</span><h1>Your games. Your circles. Your season.</h1><p>Only competitions you joined appear here. Open a game to see its card, fixtures, private table and circle conversation.</p></div><aside className={styles.identity}><span>PLAYER PROFILE</span><strong>{user?.nickname||user?.email||"Loading…"}</strong><em>{groups.length} CIRCLES · {games.length} ACTIVE GAMES</em></aside></section>{loading?<p className={styles.empty}>Loading your Arena…</p>:<section className={styles.dashboardGrid}><aside className={styles.sidebar}><span className={styles.kicker}>MY CIRCLES</span><h2>Choose a circle</h2>{groups.map(g=><button key={g.id} className={`${styles.circle} ${selected===g.id?styles.circleActive:""}`} onClick={()=>setSelected(g.id)}>{g.name}{g.is_owner?" · Admin":""}</button>)}{!groups.length&&<p className={styles.empty}>You have not joined a circle yet.</p>}</aside><div className={styles.content}><div className={styles.contentHead}><div><span className={styles.kicker}>MY COMPETITIONS</span><h2>{group?.name||"No circle selected"}</h2></div><Link href="/arena#circle">Manage circle →</Link></div>{games.length?<div className={styles.games}>{games.map(game=><Link className={styles.game} key={game.id} href={`/arena?competition=${game.id}&sport=${game.sport}&game=${game.game_type}`}><span>{game.sport.toUpperCase()} · {game.season}</span><h3>{game.name}</h3><em>{game.game_type.replace("-"," ").toUpperCase()} · {game.players} PLAYERS</em><strong>OPEN GAME ROOM →</strong></Link>)}</div>:<p className={styles.empty}>No competition has been assigned to you in this circle yet.</p>}</div></section>}<div className={styles.footerActions}><button className={styles.secondary} onClick={async()=>{await fetch("/api/arena/auth",{method:"DELETE"});location.replace("/arena/sign-in");}}>SIGN OUT</button></div></div></main>;
}